# 존재하지 않는 인덱스를 조회할 경우 IndexError가 발생한다.
# IndexError는 인덱스가 리스트의 길이를 넘어설 때 발생하며 다음과 같이 try 구문으로 에러에 대한 예외 처리를 할 수 있다.
a = [1, 2, 3, 4, 5]

try:
  print(a[9])
except IndexError:
  print('존재하지 않는 인덱스')
